services:
  mysql:
    image: mysql:8.0
    container_name: tienda-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tienda-net

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: tienda-backend-ventas
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tienda_perritos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - tienda-net

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: tienda-backend-despachos
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tienda_perritos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8082:8081"
    depends_on:
      - mysql
    networks:
      - tienda-net

  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: tienda-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - tienda-net

volumes:
  dbdata:

networks:
  tienda-net:
    driver: bridge
